spring:

  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3307/luna-message?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xxx


  mail:
    host: xxx
    name: xxx
    password: xxx
    smtp:
      ssl:
        enable: true
    username: xxx
    # redis
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  pool:
    max-active: 200.0 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 10.0 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1.0 # 连接池中的最大空闲连接
    min-idle: 0.0 # 连接池中的最小空闲连接
  timeout: 1000.0 # 连接超时时间（毫秒）


luna:
  # java mail
  mail:
    auth: xxx
    host: xxx
    mailDebug: xxx
    mailFrom: xxx
    password: xxx
    port: xxx
    protocol: xxx
    username: xxx
    # 腾讯短信
  smstencent:
    appId: xxx
    authCode: xxx
    resetPassword: xxx
    sign: xxx
    # 腾讯Api
  tencent:
    mapKey: xxx
    secretId: xxx
    secretKey: xxx
    skyEyeSecretid: xxx
    skyEyeSecretkey: xxx
    # spring mail
