spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://iszychen.club:3307/luna-message?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxx
    # redis
  redis:
    host: 47.92.89.8 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: xxx # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-idle: 8
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
  timeout: 1000.0 # 连接超时时间（毫秒）

