# \u817E\u8BAFAPi
luna.ten.secretId=xxx
luna.ten.secretKey=xxx
  # \u817E\u8BAF\u4E91\u5E02\u573AAPi
  # \u5929\u773C\u8EAB\u4EFD\u8BA4\u8BC1
luna.ten.skyEyeSecretid=xxx
luna.ten.skyEyeSecretkey=xxx
  # \u817E\u8BAF\u5730\u56FE
luna.ten.mapKey=xxx
  # redis
spring.redis.host=xxx
spring.redis.port=6379
