luna:
  ten:
    # 腾讯地图api
    mapKey: xxx
    # 腾讯api
    secretId: xxx
    secretKey: xxx
    # 腾讯市场api
    skyEyeSecretid: xxx
    skyEyeSecretkey: xxx

  #微信支付信息配置
  weixin:
    appid: xxx
    partner: xxx
    partnerkey: xxx
    notifyurl: xxx
spring:
  redis:
    host: xxx
    port: 6379
    password: xxx
  rabbitmq:
    host: xxx
    port: 5672
    username: admin
    password: xxx
server:
  port: 8080

mq:
  pay:
    exchange:
      order: exchange.order
    queue:
      order: queue.order
    routing:
      key: queue.order