luna:
  ali:
    # 阿里云oss
    bucketName: xxx
    host: xxx
    ossId: xxx
    ossKey: xxx
  alipay:
    # 应用ID
    appId: xxx
    # 异步数据返回地址
    notifyUrl: xxx
    # 私钥
    privateKey: xxx
    # 公钥
    publicKey: xxx
    # 同步返回地址
    returnUrl: xxx

