spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3307/luna-message?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxx
    # redis
luna:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: [localhost:9200]
      connect-timeout:
      socket-timeout:
      connection-request-timeout:
      index:
        number-of-replicas: 0
        number-of-shards: 3
      account:
        username: luna
        password: czy1024